### ISSUE TITLE
CobiGen CLI: Allow easy use of user's templates 

### ISSUE THREAD

**Issue by jdiazgon** [devonfw/cobigen#1108]
As a developer I want the CobiGen CLI to provide me an easy way to use my own templates so that I can generate code adapted to my project needs.

## Current version

In order to use adapted templates with our current CLI, user has two options:

- Go to CobiGen-CLI folder (e.g. devon-ide\software\cobigen-cli) and open file `pom.xml`.
- Change the `templates-devon4j` artifact to point to your Snapshot version.

Or

- Go to CobiGen-CLI folder (e.g. devon-ide\software\cobigen-cli) and open file `classPath.txt`
- Search (CTRL + F) `templates-devon4j` and you will see from which path is taking the CobiGen-CLI its templates. Change it to templates path.

Both ways are indeed hackish.
## Proposed solution
Provide a new command `cobigen adapt-templates`, similar to the functionality already existing on our Eclipse plug-in. This would create a new folder in the location of the CLI (e.g. devon-ide\software\cobigen-cli\templates) and extract the templates there, so that the CLI reads those templates and user can easily change them.

**Comment by hohwille** [comment]
@jdiazgon thanks for filing the feature request and describing the issue.

So your suggestion is that `adapt-templates` would download and extract all the templates and reconfigure cobigen-cli to use these new templates instead. Sounds like a working approach.
To make this more modular, I created issue #1109 but I better leave it out of this issue here to simplify progress.

**Comment by jdiazgon** [comment]
Exactly! Thanks for your feedback
