### ISSUE TITLE
Cobigen can not be installed into Eclipse 2020-12 (4.18.0) (from devonfw-ide-scripts-2020.12.003 )

### ISSUE THREAD

**Issue by StefanHumberg** [devonfw/cobigen#1319]
### Expected behavior

I want to install Cobigen to (devon) eclipse as described in https://devonfw.com/website/pages/docs/master-cobigen.asciidoc_eclipse-integration.html#cobigen-eclipse_installation.asciidoc_updating . 

### Actual behavior

An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.apache.xerces,2.12.1.v20210115-0812
No repository found containing: osgi.bundle,org.eclipse.emf.common,2.22.0.v20210114-1734
No repository found containing: osgi.bundle,org.eclipse.wst.sse.core,1.2.600.v202102110535
No repository found containing: osgi.bundle,org.eclipse.wst.xml.core,1.2.300.v202102110535
No repository found containing: org.eclipse.update.feature,org.eclipse.emf.common,2.22.0.v20210114-1734

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. https://devonfw.com/website/pages/docs/master-cobigen.asciidoc_eclipse-integration.html#cobigen-eclipse_installation.asciidoc_updating => Error after clicking on finish in Step 3.

### Affected version:

* OS: Windows

**Comment by MikeSchumacherCapgemini** [comment]
Hello Stefan,

I can't seem to reproduce the issue right now but when the error is what i assume it should be you will have to update using the update site (follow the instructions [here](https://devonfw.com/website/pages/docs/master-cobigen.asciidoc_eclipse-integration.html#cobigen-eclipse_installation.asciidoc_installation-steps))

This should update and install potentially missing plugins.
BUT you should not install/update the JSON-plugin because it is causing problems right now which i am currently trying to fix.

**Comment by MikeSchumacherCapgemini** [comment]
The issue mentioned above has been fixed which in turn should hopefully have fixed your issue as well, please let us know if you run into further problems
