### ISSUE TITLE
Wiki documentation needs to be overhauled

### ISSUE THREAD

**Issue by MikeSchumacherCapgemini** [devonfw/cobigen#1359]
Quite a bit of documentation in the wiki is outdated or not up-to-date. 

Things that have to be included/updated:

* Everything regarding new config reading
   - how to update old configuration to the new one (probably download new templates project or update custom templates)
   - changes in config files (or a new guide to config file(s) altogether)
   
*Acceptance Criteria Sprint 3:*

- [ ] Create list of needed changes within documentation

**Comment by Bene90** [comment]
- [ ] Create list of needed changes within documentation

**Comment by MikeSchumacherCapgemini** [comment]
In the wiki sections Configuration, Eclipse Integration, Core Plug-ins, the following problems are currently there

core-Configuration
	Configuration
		- monolithic templates are assumed, examples show single context.xml in root folder
	Context Configuration
		- MENTION NEW CONFIGURATION AFTER COBIGEN VERSION X
		- explains monolithic structure
		- more than v1.0 xsd versions exist (first paragraph also confusing)
		- trigger configuration mentions templateFolder
		- add variableAssignment mandatory attribute
		- remove incrementRef mentions
		- rewrite java template logic
		
cobigen eclipse installation
	Installation
		- phrase the remark better (cobigen installed in eclipse)
		- check necessary eclipse versions
		- update installation screenshot to install every plugin so stupid mistakes don't get made
		- Redo point 6, remove mini tutorial and reference a proper one instead
		- Generate never greyed out
		
helpful links
	- add explanations to the links
	
java plugin
	- type 'expression' better formating for valid expressions
	- do model restrictions still exist?
		
openapi plugin
	- update plugin description ("until now" kind of outdated
	- update note to add template developers
	- rewrite to describe it as an existing plugin instead of a completely new one
	- add mandatory extenstion explanation
	- fix screenshot

**Comment by GuentherJulian** [comment]
Some further problems that need to be changed (list still not complete):

### Overview section
##### Selection of current and past CobiGen applications
* Generation of EXT JS 6 is not supported anymore
* Generation of Angular client uses meanwhile Angular 13
* Mention that generation of an Ionic Client is supported

##### Guide to the reader
* Links behind “licensing of CobiGen” and “Shared Service” pointing to not existing documents

##### General CobiGen Use Cases
* Link behind “Register Factory” not working
* Link behind “devonfw wiki” not working
* Mention that client application with devon4ng also supports Ionic clients

### HowTo’s
##### Angular Client Generation
* Change Angular versions (meanwhile devon4ng uses 13)
* Change workspace image to show new template structure (context.xml in template folder)
* Update last image that shows “ng serve -o” (Angular CLI version out of date)

##### Ionic Client generation
* Link behind “You will find an example here” not working. Project with TableEto does not exist anymore, so we have to choose an other example
* Image showing how to generate from Eclipse should be updated to match with the example

##### Enterprise Architect UML diagram Generation
* Rework the “Prerequisites” section. Link behind “accumulative patch” not working (not sure why this link should be used). Steps to get the latest templates should be changed
##### CobiGen CLI Manual
* Rework commands section, some of the parameters are out of date. Suggested structure:
  * generate,g: …
    * inputFiles: …
    * --increments, -i: …
    * --templates, -t: …
    * --out, -o: …
  * adapt-templates: …
  * update, u: …
    * --all: …
  * --version, -V: …
  * --help, -h: …
  * --verbose, -v: …
  * --templates-project, -tp: …

* Update image for generate command
* Option -cl in adapt-templates command not working anymore

##### Update CobiGen
* Images show old versions. Use actual screenshots

##### .Net generation
* The guide is the one from the devon4net repository. https://github.com/devonfw/devon4net/blob/develop/documentation/howto.asciidoc#devon4net-cobigen-guide. But the CobiGen documentation still have an old version of this guide. So that guide has to be replaced with the one from devon4net
##### Release creation:
* Link behind “script” not working
* Complete section needs to be updated. There is not python file anymore
* Describe properly how to build a release with the release.sh file
##### External plugin creation
* Section “templates creation” needs to be updated to match with the new folder structure (update images and paths)


### CobiGen development
##### Dev IDE setup
* Link behind “setup the devonfw IDE” not working
* Quotation sign in step 8 not used correct
* Mark text from buttons or checkboxes in step 9 properly
* Link to contribution guide not working

##### Dependency and Licence tracking
* All the dependencies and their versions have to be checked. Some of them are outdated
* Versions of the current release have to be changed

##### Setup JRE for development
* Images are not displayed. 
* There is no folder “/software/java/additionalJdk”

**Comment by GuentherJulian** [comment]
### Implementation Docs
##### Eclipse-Plugin Development
* Link behind “Plugin.xml” not working
* Link behind “core development” not working
* Plugin.xml is out of date. Now there are four commands and handlers
* Introduction sentence in section “Handlers” says that the package workbenchcontrol contains handler for the two main use cases (generate and healthcheck). But after this all four handlers are explained. So we should mention all handlers in the introduction sentence
* Explanations for “Update Template” and “Adapt Template” are very badly formulated
* Section about GenerateHandler needs to be updated. XmlGeneratorWrapper does not exist anymore. Instead there are FileInputGeneratorWrapper and JavaInputGeneratorWrapper. UML diagram needs also to be updated
* Section about HealthCheckHandler needs to be updated. The handler does not call the execute method from HealthCheck.java. It will call execute from HealthCheckDialog, which call perform() from HealthCheck.
Also, the source code snippets are out of date
* Wizard Development:
First link does not work. Code snippets are out of date

**Comment by morsymegahed** [comment]
Here are all the broken links in the documentation:


### HowTo’s

#### Iconic client generation

- Generation

* Third and fourth link behind “here”



#### [Enterprise Architect UML diagram Generation](https://github.com/devonfw/cobigen/wiki/howto_EA-client-generation)

- Generation

* [Third](https://github.com/devonfw/devon4j/blob/develop/samples/core/src/main/java/io/devonfw/gastronomy/restaurant/tablemanagement/logic/api/to/TableEto.java) and [fourth](https://github.com/devonfw/devon4j/blob/develop/samples/core/src/main/java/io/devonfw/gastronomy/restaurant/tablemanagement/common/api/datatype/TableState.java) link behind “here”.

**Comment by morsymegahed** [comment]
Hi everyone,
this issue will be closed, because I have created an excel file with all the broken links in the CobiGen documentation that should be fixed. I also created another excel file with all above mentioned points with another new found point as well as some general notes that should also be fixed in the CobiGen documentation. The excel files have been shared in teams with the other colleages and new issues will be created to fix the mentioned points.
