### ISSUE TITLE
Template set overview

### ISSUE THREAD

**Issue by maybeec** [devonfw/cobigen#1453]
As a user, I want to get an overview of what template sets are installed including which increments are originating from which of the template sets so that I have an overview of the installed templates including increments for comparison and controlling.

**Comment by MikeSchumacherCapgemini** [comment]
Notes about this problem in regards to the CLI:
- New command to show installed template sets/increments/templates
  - add parameters to the command (show everything (tree view), show all template sets/increments of a template set/templates of an increment)
  - be able to filter through template sets/increments/templates based on specific keywords (entity related, TO related etc) (maybe reliant on #1463 to add extra data)

**Comment by MikeSchumacherCapgemini** [comment]
Notes about this problem in regard to the Eclipse integration:

- Do not show installed template sets from the generate context menu. The interface already exists in a way that would show those well but is too dependent on the input file and could confuse the user (don't generate to show what is installed)
- Maybe use UI from the generation window with template sets top level, followed by increments and then templates. See as picture below but add templates as sub-choices for increments and instead of resources to be generated give descriptions for the selected template set/increment/template

![image20](https://user-images.githubusercontent.com/38068582/155710193-8ec4f767-c95d-425f-bec9-b6b0cd83df6d.png)

**Comment by maybeec** [comment]
> Notes about this problem in regard to the CLI:
> - New command to show installed template sets/increments/templates
>   - add parameters to the command (show everything (tree view), show all template sets/increments of a template set/templates of an increment)
>   - be able to filter through template sets/increments/templates based on specific keywords (entity related, TO related etc) (maybe reliant on #1463 to add extra data)

I feel we could skip templates in a non verbose mode as normally people should focus on increments as lowest level. Nonetheless, it might be worth to see everything in a verbose mode

**Comment by maybeec** [comment]
> Notes about this problem in regard to the Eclipse integration:
> 
> - Do not show installed template sets from the generate context menu. The interface already exists in a way that would show those well but is too dependent on the input file and could confuse the user (don't generate to show what is installed)
> - Maybe use UI from the generation window with template sets top level, followed by increments and then templates. See as picture below but add templates as sub-choices for increments and instead of resources to be generated give descriptions for the selected template set/increment/template
> 
> ![image20](https://user-images.githubusercontent.com/38068582/155710193-8ec4f767-c95d-425f-bec9-b6b0cd83df6d.png)

Also here, Level of templates might be too low and less helpful for the user. I fully agree with the fact that this should be a separate dialog as it's not related to the generate dialog.
Could you try some mockup tool to share some ideas like  https://gomockingbird.com/home?

**Comment by jan-vcapgemini** [comment]
I can propose to use: https://gitlab.com/barfuin/text-tree for the tree output in CLI.
I've already played around with it a bit and prepared a simple test. The formatting options are really useful.

**Comment by MikeSchumacherCapgemini** [comment]
Here are some very rudimentary mockups. 

The first one is simply the templates and increments shown on the right with the option to select one and see its description on the right. On top there could be some description of what's going on in addition to an optional way to see the templates per increment as well

![TemplateSetDescription_NoTemplates](https://user-images.githubusercontent.com/38068582/156161641-47d57741-dacf-4286-8fcc-e8876c8bfb0f.png)

Next one is basically the same but with the "verbose" option chosen so the templates are shown as well. Descriptions for those are probably not necessary so they can't be selected.

![IncrementDescription_WithTemplates](https://user-images.githubusercontent.com/38068582/156161637-c77b13fa-c26c-406b-88a2-96388a68d00b.png)

This final one is not specifically the template overview but could be a way to download templates from a similar window. I do not think it is necessary since there is probably no proper way to show descriptions of multiple template sets and downloading them individually could be tedious for the user if they need multiple template sets (and confusion if you can download them in different ways in multiple locations)

![DownloadNewTemplates](https://user-images.githubusercontent.com/38068582/156162129-1ff3702b-5067-4676-9b32-b5f9c588c994.png)

**Comment by maybeec** [comment]
Continued in #1454
