### ISSUE TITLE
Allow adaption of template sets 

### ISSUE THREAD

**Issue by maybeec** [devonfw/cobigen#1455]
As a user, I want to be able to adapt templates so that I can change templates up to my needs for my project.
Template sets should be adaptable independently. The user needs to decide which template set she wants to adapt.

*Acceptance Criteria:*
* [ ] core is adapted and provides a proper interface and implementation to adapt any specific template set
* [ ] if a template-set to be adapted is not currently installed, core should raise an exception

**Comment by GuentherJulian** [comment]
How should we proceed if there is an old configuration with one 'big' jar file? Should the adaption work as before or should we log something like this is no longer supported and the user should update the configuration to the new structure consisting of template sets?
I think if the user has not adapted the templates until this point, then he should go with the new structure. Should the configuration be changed automatically so that the old template folder is deleted and replaced with the new structure?

**Comment by maybeec** [comment]
1. extract in old style
2. ask user to continue with upgrade of configuration (reuse #1502)
3. if confirms, trigger #1502 logic
