### ISSUE TITLE
Adapt templates adaption tests & cleanup

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/cobigen#1509]
As of #1504 the adapt templates tests were disabled.

*Acceptance Criteria*

* [x] there is at least one test testing for eclipse and cli, that the old behavior of extracting a monolithic template jar still is working (happy path only - extract - generate without exception)
* [x] further tests, which test more about the actual folder structure etc should be deleted as they would be redundant to what is implemented in core
* [x] new configuration adaptation should not be tested in eclipse / cli yet

Following tests need to be investigated

- AdaptTemplatesTest
- AdaptTemplatesCommandTest (disabled in #1520)

**Comment by maybeec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CobiGen-StoryMap-6257b8b9ecf3920015f4e871/issues/devonfw/cobigen/1509?planning-poker) with ZenHub @EduardKrieger @GuentherJulian @jan-vcapgemini @LarsReinken @mdukhan @MikeSchumacherCapgemini

**Comment by mdukhan** [comment]
My opinion is that the CLI test AdaptTemplatesTest is unnecessary and should be deleted. 
The problem is that the CLI does need a second argument in the runtime, and the reasonable solution to that is to mock the execute method which runs the command "adapt-templates" inside the CLI and instead call the methods which are responsible to adapt the templates from the source code. Which is already tested in the test extractTemplatesWithOldConfiguration. Don't you think ? 

The only usefull test then to investigate is the eclipse test.

**Comment by maybeec** [comment]
I am not 100% whether I got the point correctly, but if you ask to mock the cobigen-api adapt templates interface method to actually verify that the adaption is called correctly, I agree that this would be a proper unit test which does not have any overlap with existing tests of cobigen core.

Nonetheless, mocking always leaves a gap on integration. Therefore, I would recommend to also have an integration test really testing that template adaption was executed. For sure this does not mean that you need to verify again the whole template outcome. But you could at least check that a certain folder has been extracted and possibly the pom within this folder is the same coming from the jar. Nothing more to make tests less redundant.
