### ISSUE TITLE
Automatically ask for upgrade on reading monolithic templates from a folder

### ISSUE THREAD

**Issue by maybeec** [devonfw/cobigen#1518]
As a cobigen user, I want to get automatically informed about the conceptual changes of the configuration going from monolithic template configuration folder to a modular template-set configuration folder. I want to get offered information (#1531) as well as an automatic upgrade as far as possible (#1502).

*Acceptance Criteria*
* [x] eventually, I would like to get the option to perform the automated upgrade step
* [x] I want to also get an option to postpone the upgrade for 30 days
* [x] after upgrade / no upgrade, the generation will be executed as requested by the user initially
* [x] After upgrading to the new configuration, the configuration should be re-read and also used
* [x] Make sure, that you tested the cases for aborting generation as of deprecated configuration as well as testing forced generation with deprecated configuration
* [x] Make sure that you activated all disabled tests from #1502 and #1552

**Comment by maybeec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CobiGen-StoryMap-6257b8b9ecf3920015f4e871/issues/devonfw/cobigen/1518?planning-poker) with ZenHub @EduardKrieger @GuentherJulian @jan-vcapgemini @LarsReinken @mdukhan @MikeSchumacherCapgemini

**Comment by mdukhan** [comment]
What do we do if we have in the Cobigen Homepath the two monolithic and the new template-sets folders? 

Should we recommend an upgrade for the monolithic templates? Or should this case be ignored? 

This case, I believe, should be ignored. Otherwise, we risk receiving an infinite number of upgrade warning messages. In this case, the template-set should be preferred.

Any suggestions?
