### ISSUE TITLE
Implement smoketests for all templates

### ISSUE THREAD

**Issue by maybeec** [devonfw/cobigen#427]
We should have a smoketest for all templates assuring, that there are no exceptions on generation of each template.

**Comment by Richter-cg** [comment]
Tests exist & green:
- [ ] ToInput
- [ ] OpenApiIput
- [ ] XML
- [ ] EtoInput
- [ ] RestServiceInput      (fails on my machine)
- [ ] EntityInput

**Comment by jdiazgon** [comment]
Actually, I saw that you are using an UML xml file as input for the tests. We decided to only use the templates related to the `Entity infrastructure` increment:

- ApplicationPersistenceEntity
- ApplicationEntity
- {variables.className}Entity
- {variables.className}

The rest will be discarded because we are trying to implement a multi-step generation. See [this project](https://github.com/devonfw/tools-cobigen/projects/8) and [this issue](https://github.com/devonfw/tools-cobigen/issues/676).

**Comment by maybeec** [comment]
We have at least smoke tests meanwhile generating all templates within the templates project to assure that there is at least no error on initial generation.
